Revamp PDE::initialize()
Use non-empty braced initializer list in Transport::output() to call
initialize() with unused arguments. See also
http://stackoverflow.com/a/26949099

Thanks to clang 3.9 for the error:

In file included from /tmp/TeamCity-15/work/4b318255fc6b9ff5/src/PDE/PDEStack.C:24:
/tmp/TeamCity-15/work/4b318255fc6b9ff5/src/PDE/Transport.h:354:30: error: chosen constructor is explicit in copy-initialization
      initialize( coord, {}, {}, U, t );