Spell out type instead of empty initializer list for Progress ctor default argument
Doubly-braced initializer list breaks gcc 4.8.5 with

/scratch/jbakosi/code/quinoa/src/Inciter/Transporter.C:95:45: internal compiler error: in reshape_init_r, at cp/decl.c:5431
               {{ "r", "a", "s", "l", "p" }} )

while singly-braced initializer list breaks it with

/tmp/TeamCity-15/work/4b318255fc6b9ff5/src/Inciter/Transporter.C: In constructor ‘tk::Progress<N>::Progress(const tk::Print&, bool, std::array<std::basic_string<char>, N>&&, std::array<int, N>&&) [with long unsigned int N = 3ul]’:
/tmp/TeamCity-15/work/4b318255fc6b9ff5/src/Inciter/Transporter.C:95:45: error: missing initializer for member ‘std::array<int, 3ul>::_M_elems’ [-Werror=missing-field-initializers]
               {{ "r", "a", "s", "l", "p" }} )
                                             ^
No problem with gcc 6.2 with any of the above so we keep the one that
works with the old version.