Attempt at fixing the hdf5 link line
This is an attempt to fix the problem occurred somewhere between
9860ce67 (fails) and 06c56ec7 (worked), thanks to TeamCity for a quick
diagnosis.

The problem only appeared inside the alpine container doing a fully
static build with the error:

[14:49:17] :     [Step 2/4] [ 90%] Linking CXX executable unittest
[14:49:17] :     [Step 2/4] /home/quinoa/quinoa/tpl/install/gnu-x86_64/charm/bin/charmc -module DistributedLB -c++ /opt/openmpi/bin/mpicxx  -Werror -fdiagnostics-color -Wall -Wextra -pedantic -pedantic-errors -Wcast-align -Wcast-qual -Wdisabled-optimization -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wimport -Winit-self -Winvalid-pch -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wstack-protector -Wstrict-aliasing=2 -Wswitch-default -Wunreachable-code -Wunused -Wunused-parameter -Wvariadic-macros -Wwrite-strings -Wno-sign-compare -Wno-unused-function -Wno-stack-protector -O3 -DNDEBUG  -Wno-unused-parameter -rdynamic -static CMakeFiles/unittest.dir/UnitTestDriver.C.o CMakeFiles/unittest.dir/UnitTest.C.o  -o unittest ../Base/libBase.a ../IO/libMeshIO.a ../Mesh/libMesh.a ../RNG/libRNG.a ../LoadBalance/libLoadBalance.a ../UnitTest/libUnitTest.a ../Control/libUnitTestControl.a /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib64/libpugixml.a /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libexodus.a /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib64/librngsse.a /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libH5Part.a /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libnetcdf.a /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libhdf5.a -lz -ldl -lm -lz /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libhdf5_hl.a /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libaec.a -ldl -lm /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libhdf5_hl.a /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libaec.a
[14:49:18] :     [Step 2/4] /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libhdf5_hl.a(H5LT.o): In function `H5LT_dtype_to_text':
[14:49:18] :     [Step 2/4] H5LT.c:(.text+0x3442): undefined reference to `H5Tget_tag'
[14:49:18] :     [Step 2/4] /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libhdf5_hl.a(H5LTparse.o): In function `H5LTyyparse':
[14:49:18] :     [Step 2/4] H5LTparse.c:(.text+0x1129): undefined reference to `H5Tset_tag'
[14:49:18] :     [Step 2/4] collect2: error: ld returned 1 exit status
[14:49:18] :     [Step 2/4] Fatal Error by charmc in directory /home/quinoa/quinoa/build/Main

The cause of the problem appears to be the different order produced by
cmake's FindHDF5.cmake:

works:
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
[17:41:46][Step 2/4] -- Found HDF5: /lib/libz.a;/usr/lib/libdl.a;/usr/lib/libm.a;/home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libhdf5.a (found version "1.8.16") found components:  C HL

fails:
- HDF5: Using hdf5 compiler wrapper to determine C configuration
[14:47:42][Step 2/4] -- Found HDF5: /home/quinoa/quinoa/tpl/install/gnu-x86_64/lib/libhdf5.a;/lib/libz.a;/usr/lib/libdl.a;/usr/lib/libm.a (found version "1.8.16") found components:  C HL

According to https://gitlab.kitware.com/cmake/cmake/issues/16657, cmake
v3.8 does produce a different link order for HDF5-related libraries
compared to cmake 3.7, changed in
https://gitlab.kitware.com/cmake/cmake/commit/ae89967f9dc9308003630531ef34764030f98bd0,
which was the one used by alpine in the last successful build.

The fix is to reorder the link line which now apparently allows omitting
zlib too.