Make sure both tpl and code builds pick up static libs for the static build
Seems broken though, tested on two linux machines:

kosi@lagrange:~/code/quinoa/build/gnu:master$ ninja meshconv
[31/31] Linking CXX executable Main/meshconv
FAILED: : && /home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/charm/bin/charmc  -Wall -pedantic -Wextra -Wshadow -Wformat -Wsign-compare -Wpointer-arith -Winvalid-pch -Wcast-align -Wwrite-strings -Wunused -Woverloaded-virtual -fdiagnostics-show-option -Wno-vla -Wno-literal-suffix -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -fdiagnostics-color -Wconversion -Wno-comment -DMKL_ILP64 -m64 -O3 -DNDEBUG  -static   -Wno-unused-parameter Main/CMakeFiles/meshconv.dir/MeshConvDriver.C.o Main/CMakeFiles/meshconv.dir/MeshConv.C.o  -o Main/meshconv  -rdynamic IO/libIO.a Mesh/libMesh.a Control/libMeshConvControl.a Base/libBase.a -lpugixml /home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/lib/libnemesis.a /home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/lib/libexodus.a /home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/lib/libexodus.a /home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/lib/libnetcdf.a /usr/lib/x86_64-linux-gnu/hdf5/openmpi/lib/libhdf5_hl.a /usr/lib/x86_64-linux-gnu/hdf5/openmpi/lib/libhdf5.a -lsz -lz -ldl -lm -laec -Wl,-rpath,:::::::::::::: && :
/usr/lib/x86_64-linux-gnu/hdf5/openmpi/lib/libhdf5.a(H5PL.o): In function `H5PL__open':
/build/hdf5-1.8.16+docs/debian/build-openmpi/src/../../../src/H5PL.c:596: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/openmpi/1.10.2/gnu/system/lib/libopen-rte.a(session_dir.o): In function `orte_session_dir_get_name':
session_dir.c:(.text+0x201): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/openmpi/1.10.2/gnu/system/lib/libopen-pal.a(if.o): In function `opal_ifaddrtoname':
if.c:(.text+0x260): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/charm/bin/../lib/libconv-util.a(sockRoutines.o): In function `skt_lookup_ip':
sockRoutines.c:(.text+0x30c): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/openmpi/1.10.2/gnu/system/lib/libopen-pal.a(evutil.o): In function `evutil_unparse_protoname':
/home/jbakosi/code/etc/thirdparty/openmpi/openmpi-1.10.2/opal/mca/event/libevent2021/libevent/evutil.c:758: warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `alloc_zero_based_socket':
(.text+0x25): undefined reference to `nl_socket_alloc'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_mcast_mac_ipv6':
(.text+0x60): undefined reference to `nl_addr_get_binary_addr'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_mcast_mac_ipv6':
(.text+0x79): undefined reference to `nl_addr_build'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_link_local_mac_ipv6':
(.text+0x9d): undefined reference to `nl_addr_get_binary_addr'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_link_local_mac_ipv6':
(.text+0xb6): undefined reference to `nl_addr_get_binary_addr'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_link_local_mac_ipv6':
(.text+0xdc): undefined reference to `nl_addr_build'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x115): undefined reference to `rtnl_route_get_pref_src'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x120): undefined reference to `rtnl_route_get_type'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x12d): undefined reference to `rtnl_route_nexthop_n'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x141): undefined reference to `rtnl_route_nh_get_gateway'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x14c): undefined reference to `rtnl_route_nh_get_ifindex'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x15c): undefined reference to `nl_addr_put'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x164): undefined reference to `nl_addr_clone'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x18d): undefined reference to `nl_addr_put'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x1c0): undefined reference to `nl_addr_clone'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x203): undefined reference to `nl_addr_get_family'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x266): undefined reference to `nl_addr_build'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x27e): undefined reference to `nl_addr_set_prefixlen'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':
(.text+0x286): undefined reference to `nl_addr_get_prefixlen'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libibverbs.a(src_libibverbs_la-neigh.o): In function `get_route_cb_parser':

...

and

[31/31] Linking CXX executable Main/meshconv
FAILED: : && /home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/charm/bin/charmc  -Wall -pedantic -Wextra -Wshadow -Wforma
lign -Wwrite-strings -Wunused -Woverloaded-virtual -fdiagnostics-show-option -Wno-vla -Wno-literal-suffix -Wno-unused-lo
rations -fdiagnostics-color -Wconversion -Wno-comment -O3 -DNDEBUG  -static   -Wno-unused-parameter Main/CMakeFiles/mesh
r/MeshConv.C.o  -o Main/meshconv  -rdynamic IO/libIO.a Mesh/libMesh.a Control/libMeshConvControl.a Base/libBase.a -lpugi
b/libnemesis.a /home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/lib/libexodus.a /home/jbakosi/code/quinoa/tpl/install/gn
install/gnu-x86_64/lib/libnetcdf.a /home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/lib/libhdf5_hl.a /home/jbakosi/code/
m -laec -Wl,-rpath,:::::::::::::: && :
/home/jbakosi/code/quinoa/tpl/install/gnu-x86_64/lib/libhdf5.a(H5PL.o): In function `H5PL_load':
H5PL.c:(.text+0x63c): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries
/usr/bin/ld: cannot find -lOpenCL