Add extra dependency of LinSysMerger charm module on Performer charm module
This should fix the following issue:

In file included from /home/travis/build/jbakosi/quinoa/src/Inciter/Performer.h:35:0,
                 from /home/travis/build/jbakosi/quinoa/src/LinSys/LinSysMerger.h:38,
                 from /home/travis/build/jbakosi/quinoa/src/LinSys/LinSysMerger.C:12:
/home/travis/build/jbakosi/quinoa/build/Main/inciter.decl.h:7:28: fatal error: performer.decl.h: No such file or directory
 #include "performer.decl.h"
                            ^
compilation terminated.
make[2]: *** [LinSys/CMakeFiles/LinSys.dir/LinSysMerger.C.o] Error 1
make[1]: *** [LinSys/CMakeFiles/LinSys.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Making LinSysMerger charm module dependent on Performer charm module makes sense
since LinSysMerger is specialized on CProxy_Performer. This manual cmake depency
is needed, since cmake cannot know what charmc will generate. This is required
to make sure performer.decl.h is generated before linsysmerger.ci is processed
during the build, as LinSysMerger is specialized on CProxy_Performer. This is
similar to LinSysMerger's dependency on its other template argument, currently
specialized Conductor_Proxy.

This change also required removing the dependency of Performer charm module on
LinSysMerger charm module as that, together with the above, would yield a cyclic
dependency.

This fix appears to work fine locally, let's see if the Travis build likes it as
well.