Undefine macro 'I' before including boot/variant
This is a similar fix to 41b2f79, which was also highly counter-intuitive based
on the error message as the error appears to come from complex.h or lapacke.h,
in neither of which I can find a macro definition for 'I'.

Symptom:

=======================
In file included from /usr/include/c++/8.2.0/complex.h:38,
                 from /home/quinoa/tpl/gnu/include/lapacke.h:73,
                 from /home/quinoa/quinoa/src/UnitTest/tests/RNG/TestRNG.h:28,
                 from /home/quinoa/quinoa/src/UnitTest/tests/RNG/TestRandom123.C:17:
/usr/include/boost/container_hash/extensions.hpp:185:31: error: expected ')' before '__extension__'
         template <std::size_t I, typename T>
                               ^
/usr/include/boost/container_hash/extensions.hpp:185:31: error: expected '>' before '__extension__'
/usr/include/boost/container_hash/extensions.hpp:185:31: error: expected unqualified-id before ')' token
         template <std::size_t I, typename T>
                               ^
/usr/include/boost/container_hash/extensions.hpp:192:31: error: expected ')' before '__extension__'
         template <std::size_t I, typename T>
                               ^
/usr/include/boost/container_hash/extensions.hpp:192:31: error: expected '>' before '__extension__'
/usr/include/boost/container_hash/extensions.hpp:192:31: error: expected unqualified-id before ')' token
         template <std::size_t I, typename T>
                               ^
In file included from /usr/include/boost/container_hash/hash.hpp:760,
                 from /usr/include/boost/type_index/stl_type_index.hpp:43,
                 from /usr/include/boost/type_index.hpp:29,
                 from /usr/include/boost/variant/variant.hpp:21,
                 from /usr/include/boost/variant.hpp:17,
                 from /home/quinoa/quinoa/src/NoWarning/variant.h:30,
                 from /home/quinoa/quinoa/src/Base/PUPUtil.h:17,
                 from /home/quinoa/quinoa/src/Control/Options/RNGSSESeqLen.h:16,
                 from /home/quinoa/quinoa/src/RNG/RNGSSE.h:21,
                 from /home/quinoa/quinoa/src/UnitTest/tests/RNG/TestRNG.h:43,
                 from /home/quinoa/quinoa/src/UnitTest/tests/RNG/TestRandom123.C:17:
/usr/include/boost/container_hash/extensions.hpp: In function 'std::size_t boost::hash_detail::hash_tuple(const T&)':
/usr/include/boost/container_hash/extensions.hpp:205:33: error: 'hash_combine_tuple' is not a member of 'boost::hash_detail'
             boost::hash_detail::hash_combine_tuple<0>(seed, v);
=======================

Anyway, this is a work-around, and now we have two of these:

src$ rgrep -Ii 'undef I'
NoWarning/variant.h:#undef I
NoWarning/set.h:#undef I