Switch extern module to an include
CMake definitely does not detect a dependency originating from a Charm++
interface file via "extern module". This commit apparently successfully switches
the extern module in particlewriter.ci to an include in ParticleWriter.h, which
is (should be) correctly detected by cmake and preventing build errors like

In file included from LoadBalance/../IO/particlewriter.decl.h:7:0,
                 from <quinoa>/src/NoWarning/particlewriter.decl.h:54,
                 from <quinoa>/src/IO/ParticleWriter.h:18,
                 from <quinoa>/src/IO/ParticleWriter.C:13:
Inciter/conductor.decl.h:7:31: fatal error: linsysmerger.decl.h: No such file or directory
compilation terminated.

I wonder if all or at least some extern module declarations can be switched in a
similar fashion, which would eliminate manual add_dependencies() cmake calls.