Put back reducing opt level for clang-release build
In an attempt to make clang successfully link the inciter executable.

Currently, clang 3.8 fails to link inciter with -O3 producing errors due to
failing to find SDAG code in LinSysMerger. Errors only with clang, only with opt
level larger than -O0.

Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4filllhs()'
Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4fillsol()'
Inciter/libInciter.so: undefined reference to `inciter::Partitioner<inciter::CProxy_Conductor, inciter::CProxy_Performer, tk::CProxy_LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>>::wait4bounds()'
Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4sol()'
Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4rhs()'
Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4hyprelhs()'
Inciter/libInciter.so: undefined reference to `inciter::Partitioner<inciter::CProxy_Conductor, inciter::CProxy_Performer, tk::CProxy_LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>>::wait4prep()'
Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4lhs()'
Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4asm()'
Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4fillrhs()'
Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4hyprerhs()'
Inciter/libInciter.so: undefined reference to `tk::LinSysMerger<inciter::CProxy_Conductor, inciter::CProxy_Performer>::wait4hypresol()'