Fix ncomp_t
Mac/clang caught that ncomp_t wasn't consistent throughout:

The error was:

/Users/travis/build/jbakosi/quinoa/src/DiffEq/InitPolicy.h:116:26: error: no
matching function for call to 'min'
    const ncomp_t size = std::min( ncomp, spike.size() );

due to:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2544:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('unsigned long long' vs. 'unsigned long')
min(const _Tp& __a, const _Tp& __b)

where ncomp was uint64_t, while spike.size() was std::size_t. Apparently
std::size_t != uint64_t on mac.

This commit changes kw::ncomp::info::expect::type = std::size_t, which should
fix the above inconsistency on mac.